#The /efs/wordpress/config/uploads.ini contains this one line "upload_max_filesize = 16M"

version: '3'

services:

   wordpress:
     image: wordpress:latest
     deploy:
       replicas: 2
       restart_policy:
        condition: on-failure
     volumes:
       - /efs/wordpress/www:/var/www/html
       - /efs/wordpress/config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: appname.abcde12345678.ap-southeast-2.rds.amazonaws.com:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password
     networks:
       - wordpress

networks:
  wordpress:
    external:
      name: wordpress
