version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - wordpress2_db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PASSWORD
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: PASSWORD

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - wordpress2:/var/www/html
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: PASSWORD
volumes:
  wordpress2_db:
    driver: local-persist
    driver_opts:
      mountpoint: /data/wordpress2/var/lib/mysql
  wordpress2:
    driver: local-persist
    driver_opts:
      mountpoint: /data/wordpress2/var/www/html
