version: '3'

services:
   db:
     image: mysql:5.7
     deploy:
       replicas: 1
       restart_policy:
        condition: on-failure
     volumes:
       - dbdata:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     deploy:
       replicas: 2
       restart_policy:
        condition: on-failure
     volumes:
       - html:/var/www/html
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password
volumes:
    dbdata:
    html:
