#### docker-compose.yaml 
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: password

   wordpress:
     depends_on:
       - db
     build: .
     volumes:
       - html:/var/www/html
     ports:
       - "9080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: password
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     environment:
      - PMA_HOST=db
     restart: always
     ports:
      - 9081:80
     volumes:
      - sessions:/sessions
      - config:/etc/phpmyadmin/config.user.inc.php
      - theme:/www/themes/theme
volumes:
    dbdata:
    html:
    sessions:
    config:
    theme:

#### Dockerfile
FROM wordpress:latest
RUN apt-get update \
 && apt-get install -y git zlib1g-dev php7.0/stable php7.0/stable php7.0-fpm/stable php7.0-cgi/stable php7.0-cli/stable php7.0-opcache/stable php7.0-readline/stable php7.0-json/stable \
 && docker-php-ext-install pdo pdo_mysql zip
